### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by muf** [muf/Orion#13]
- [ ] 랜 선 모듈 증발..
- [ ] 휴지 10개 미만으로 남음
- [ ] 방 전체 점검좀 하자 . 남아나는게 없는 거 같다.
- [ ] 운동좀 해야하는데
- [ ] 스텐드 살래
- [ ] 가계부좀 관리 방법좀 생각 - 후 뭐 없나.
- [ ] 이불 커버.. 집에 가면 받아오자. 집에 가면 노트 놓고 온 것도 챙겨야함
- [ ] 치과 점검 받아야하는데.. ㄹㅇ 받자

**Comment by muf** [comment]
- [ ] 집에 가면 의자좀 가져오자 책상 +1 고민해보고 의자는 진짜 가져오자

**Comment by muf** [comment]
- [ ] V3 재계약 아빠 노트북 보안 설치

**Comment by muf** [comment]
의자 / 책상 / 이불커버 / 커피 / 빵 / 치즈 /

**Comment by muf** [comment]
- [ ] 극세사 밀걸레 사자.

**Comment by muf** [comment]
- [ ] 당뇨 / 탄수화물 중독 / 운동

**Comment by muf** [comment]
- [ ] 코스트코 스테이크용 대구살 냉동 !
- [ ] 감자?! 양파 당근?!
